### ISSUE TITLE
View engine error. 

### ISSUE THREAD

**Issue by anirudhravichandran** [AbdealiJK/dashboard#16]
404 Error: No default engine was specified and no extension was provided. The line is app.set('view engine','ejs'); (coming after the 404 definition).

**Comment by AbdealiJK** [comment]
Did you add the view engine line in app.js ?

**Comment by anirudhravichandran** [comment]
Both in line 42 and 77.

**Comment by AbdealiJK** [comment]
Ok ... you don't need to add it in 2 places ... can you copy paste the line here ?

**Comment by anirudhravichandran** [comment]
app
  .use(function (req, res) {
    res.status(404).render('pages/404', {title: 'Not Found :('});
  })
	.set('view engine','ejs'); -->i added.

**Comment by AbdealiJK** [comment]
Did you restart grunt after you added that ?

**Comment by AbdealiJK** [comment]
Also, when adding code do it like : 
```
this
```

This can be done by putting 3 backticks ( ` ) before and after your code

**Comment by anirudhravichandran** [comment]
I added grunt. I didn't get the above method though.

**Comment by AbdealiJK** [comment]
Can you post the exact error you are seeing ?

Ill tell u about the backtick thing on google hangout

**Comment by anirudhravichandran** [comment]
404 Error: No default engine was specified and no extension was provided.
at new View (/home/anirudh/dashboard/node_modules/express/lib/view.js:41:42)
at Function.app.render (/home/anirudh/dashboard/node_modules/express/lib/application.js:484:12)
at ServerResponse.res.render [as _EDT_orig_render] (/home/anirudh/dashboard/node_modules/express/lib/response.js:777:7)
at ServerResponse.render (/home/anirudh/dashboard/node_modules/express-debug/lib/response.js:116:34)
at Layer.app.locals.config [as handle] (/home/anirudh/dashboard/app.js:77:21)
at trim_prefix (/home/anirudh/dashboard/node_modules/express/lib/router/index.js:226:17)
at c (/home/anirudh/dashboard/node_modules/express/lib/router/index.js:198:9)
at Function.proto.process_params (/home/anirudh/dashboard/node_modules/express/lib/router/index.js:251:12)
at next (/home/anirudh/dashboard/node_modules/express/lib/router/index.js:189:19)
at next (/home/anirudh/dashboard/node_modules/express/lib/router/index.js:150:14)

**Comment by AbdealiJK** [comment]
So ... this doesnt seem to be an error in your code ... its an error in EDT
- Express Debug Toolbar

Can you comment that portion out and try ?
https://github.com/AbdealiJK/dashboard/blob/master/app.js#L88

**Comment by anirudhravichandran** [comment]
the same error without the edt line.

**Comment by AbdealiJK** [comment]
can you try putting "404.ejs" ?

**Comment by anirudhravichandran** [comment]
where? in this comment?

**Comment by AbdealiJK** [comment]
In app.js there will be a line saying something like :
https://github.com/AbdealiJK/dashboard/blob/master/app.js#L77

**Comment by chinnichaitanya** [comment]
I think I the order should be 
```
.set('view engine','ejs'); -->i added.

app
.use(function (req, res) {
res.status(404).render('pages/404', {title: 'Not Found :('});
})
```
Try changing the order of the above two lines

**Comment by chinnichaitanya** [comment]
Any updates on this ?
Is this problem solved ?

**Comment by anirudhravichandran** [comment]
Problem Solved.

**Comment by AbdealiJK** [comment]
Close the issue

**Comment by chinnichaitanya** [comment]
Comment how did you solve it. It might help others.
