### ISSUE TITLE
problem in creating form

### ISSUE THREAD

**Issue by karthikvijay** [AbdealiJK/dashboard#18]
whenever after entering details in the form and press enter error of createAlert is not defined is coming.

**Comment by AbdealiJK** [comment]
That would mean you arent using the "require" function to include the file
where the function "createAlert" is defined

**Comment by karthikvijay** [comment]
no it has been included

**Comment by AbdealiJK** [comment]
Can you show the error and the file where it is showing the error ?

Better if you can push your code to a new branch

**Comment by karthikvijay** [comment]
i craeted a new branch application
and i wrote git push origin application and it is not working

**Comment by AbdealiJK** [comment]
We cant help unless you give a proper error message

Meet chinni or deepak if you cant solve git problems

**Comment by karthikvijay** [comment]
after entering in the form and clicking submit button, this is the error which comes up
```
 createAlert is not defined
    at Object.exports.mongoErrorsToAlert (/home/han/dashboard_old/helpers/messages.js:18:10)
    at /home/han/dashboard_old/controllers/user.js:35:41
    at handleError (/home/han/dashboard_old/node_modules/mongoose/node_modules/hooks/hooks.js:92:18)
    at _next (/home/han/dashboard_old/node_modules/mongoose/node_modules/hooks/hooks.js:34:22)
    at fnWrapper (/home/han/dashboard_old/node_modules/mongoose/node_modules/hooks/hooks.js:159:8)
    at complete (/home/han/dashboard_old/node_modules/mongoose/lib/document.js:986:5)
    at /home/han/dashboard_old/node_modules/mongoose/lib/document.js:977:20
    at ObjectId.SchemaType.doValidate (/home/han/dashboard_old/node_modules/mongoose/lib/schematype.js:603:22)
    at /home/han/dashboard_old/node_modules/mongoose/lib/document.js:968:9
    at process._tickCallback (node.js:415:13)
 Use --force to continue.

```

**Comment by AbdealiJK** [comment]
You can see the topmost line which says : 
```at Object.exports.mongoErrorsToAlert (/home/han/dashboard_old/helpers/messages.js:18:10)```
So, that means that nodejs knows to search for the function in helpers/messages ....

But, it cannot find it there .... 

In github i can see that it is defined here : https://github.com/AbdealiJK/dashboard/blob/master/helpers/messages.js#L2

Which means in your local repository you may have deleted the function ... can you show me your "helpers/messages.js"

**Comment by karthikvijay** [comment]
This is actually my helpers/messages.js
```
exports.createAlert = function(type, message) {
  return { 'type': type, 'body': message };
}

exports.mongoErrorsToAlert = function (errors) {
  var keys = Object.keys(errors)

  if (!keys) {
    return createAlert('')
  }
  var body = ''
  keys.forEach(function (key) {
    if (errors[key]) {
      body += key + ' - ' + errors[key].message + '<br />';
    }
  })
  return createAlert('error', body);
}
```

**Comment by AbdealiJK** [comment]
Hm ... ok .... thats weird.

Can you show user.js ?

**Comment by karthikvijay** [comment]
this is controllers/user.js
```

var messageHelper = require('../helpers/messages'),
    userModel = require('../models/user'),
    config = require('../configs/config');

exports.loginGet = function (req, res) {
  res.render('pages/login', {
    title: 'Login',
   // csrfToken: req.csrfToken(),
    message: req.session.flash
  });
};
exports.loginPost = function (req, res) {
  userModel.find({'email': req.body.email}, function(err, users) {
    if( !err ) {
      req.session.flash = messageHelper.createAlert('success', 'You have been logged in !');
      console.log(users);
      return res.redirect(config.baseUrl);
    } else {
      req.session.flash = messageHelper.mongoErrorsToAlert(err);
      console.log(err);
      return res.redirect(config.baseUrl);
    }
  });
};

exports.register = function (req, res) {
  // console.log(req.body);
  var user = new userModel(req.body);
  user.save(function(err) {
    if ( ! err ) {
     req.session.flash = messageHelper.createAlert('success', 'Your account has been created !');
      return res.redirect(config.baseUrl);
    } else {
      req.session.flash = messageHelper.mongoErrorsToAlert(err);
      console.log(err);
      return res.redirect(config.baseUrl);
    }
  });
};

```

**Comment by AbdealiJK** [comment]
Hm ... not sure ....
Maybe the code i wrote doesnt work.

Can you write ur own code for the logic ? put console.logs and see whats the error

**Comment by AbdealiJK** [comment]
CLose this issue if its fixed
