### ISSUE TITLE
problem in listing details

### ISSUE THREAD

**Issue by karthikvijay** [AbdealiJK/dashboard#21]
I have written the code to show details of all applicants. This is the code of the correponding ejs file
```

<div class="container">
<h3>Core Administration</h3>
<table class='table'>
<tr>
<th>Name</th>
<th>Email_ID</th>
<th>RollNo</th>
<th>Department</th>
<th></th>
<th></th>
</tr>


<% _.each(applications, function(application) { %>
<tr data-id="<%= application.id %>" data-model="application">

<td><%= application.name %></td>
<td><%= application.email %></td>
<td><%= application.rollno %></td>
<td><%= application.department %></td>

<td><a href="/application/edit/<%= user.id %>" class="btn btn-sm btn-warning">Edit</a></td>
<td><form action="/application/download/<%= application.id %>" method="POST">

</form></td>
</tr>
<% }) %>
</table>
</div>

```
I am getting the following error
```
{ [ReferenceError: /home/han/dashboard_old/views/application/details.ejs:15
    13| 
    14| 
 >> 15| <% _.each(applications, function(application) { %>
    16| <tr data-id="<%= application.id %>" data-model="application">
    17| 
    18| <td><%= application.name %></td>

_ is not defined]
  path: '/home/han/dashboard_old/views/application/details.ejs' }
ReferenceError: /home/han/dashboard_old/views/application/details.ejs:15
    13| 
    14| 
 >> 15| <% _.each(applications, function(application) { %>
    16| <tr data-id="<%= application.id %>" data-model="application">
    17| 
    18| <td><%= application.name %></td>

_ is not defined
    at eval (eval at <anonymous> (/home/han/dashboard_old/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:29:337)
    at eval (eval at <anonymous> (/home/han/dashboard_old/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:29:1095)
    at /home/han/dashboard_old/node_modules/ejs/lib/ejs.js:255:15
    at Object.exports.render (/home/han/dashboard_old/node_modules/ejs/lib/ejs.js:293:13)
    at View.exports.renderFile [as engine] (/home/han/dashboard_old/node_modules/ejs/lib/ejs.js:323:20)
    at View.render (/home/han/dashboard_old/node_modules/express/lib/view.js:76:8)
    at Function.app.render (/home/han/dashboard_old/node_modules/express/lib/application.js:502:10)
    at ServerResponse.res.render [as _EDT_orig_render] (/home/han/dashboard_old/node_modules/express/lib/response.js:777:7)
    at ServerResponse.render (/home/han/dashboard_old/node_modules/express-debug/lib/response.js:116:34)
    at Promise.foundApplications (/home/han/dashboard_old/controllers/application.js:24:5)
GET /application/details 500 76ms

```
I don't know how to include the underscore thing.

**Comment by AbdealiJK** [comment]
_.each is a for loop ...

You can write a simple for loop of your own.
http://stackoverflow.com/questions/22952044/loop-through-json-in-ejs
